ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

server:
  port: '@project.port@'
spring:
  application:
     name: zerody-user-system
  profiles:
     active: '@project.active@'
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zerody!@#456
    host: 10.66.50.241:3306
    url: jdbc:mysql://${spring.datasource.host}/zero_user?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    filters: stat
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  typeAliasesPackage: com.zerody.user.pojo
  typeHandlersPackage: com.zerody.user.enums.typeHandler
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
logging:
  level:
    com:
      zerody: info
    root: info
  file: '@project.log@zerody-user.log'
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}][%X{spanId}] [%thread]%-5level%X{req.remoteHost}%X{req.requestURI} %logger{35}- %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread]%-5level%X{req.remoteHost}%X{req.requestURI} %logger{35}- %msg%n'

  #文件上传路径
upload:
    path: /home/docker/static

### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
xxl:
  job:
    admin:
      addresses: http://10.66.50.236:9080/xxl-job-admin
### 执行器通讯TOKEN [选填]：非空时启用；
    #accessToken=
### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
    executor:
      appname: ${spring.application.name}
### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 1${server.port}
### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30


sms:
  template:
    public: SMS_210065852
    userTip: SMS_209832463
#IdGenerator
workerId: 1
shardId: 4

#导入记录
import:
  deleted:
    day: 15

flow:
  oaCompany: oa-flow-001
  oaCompanyName: OA审批企业
  client:
    clientId: user
    secret: aaa
  message-queue: message-queue
  clientId: bonade
  # 二版审批系统服务地址：提供审批相关服务
  server:
    host: http://192.168.100.15:9009
    gateway: /workflow
  #休眠时间：单位毫秒 （不配置，则默认是 30秒）
  registry:
    sleep-time: 10000
  # MQ地址
  rabbitmq:
    host: 10.66.50.235
    port: 5672
    username: zerody_admin
    password: zerody_test
msg:
  opinion:
    url: /home/suggestion/detail
    query: '{"fromPage":"boxSuggestion","id":"${id}"}'
    arguments:
    title: '意见查看提醒'
    title2: '意见提交回复提醒'
    content: '${userName}向你提出了一个意见或建议，请及时查看!'
    content2: '${userName}已经回复了你提出的意见或建议，请及时查看!'
  entry:
    url: /home/anniversary/celebration/notice
    query: '{"importCustomerNum":"${importCustomerNum}","loansMoney":"${loansMoney}","signOrderNum":"${signOrderNum}","content":"${content}","blessing":"${blessing}}"}'
    arguments:
    title: '入职周年祝贺'
    content: ''
    content2: ''
  loan:
    url: /data/analysis/sign/list
    query: '{"type":"%s","userId":"%s","departId":"%s","companyId":"%s"}'
    arguments:
    title: '客户跟进提醒'
    content: '【%s】伙伴已解约，他最近的签单客户由您继续服务，已通过短信通知客户，请留意客户咨询来电！'
  superior:
    url: /data/analysis/sign/list
    query: '{"type":"%s","userId":"%s","departId":"%s","companyId":"%s"}'
    arguments:
    title: '客户跟进提醒'
    content: '【%s】伙伴已解约，他最近的签单客户由他的团队长跟进，请做好监督，预防客户流失!'
  # boss账号接收
  boss-receive-opinion:
    url:
    url2:
    query: '{"userId":"${userId}",}'
    arguments:
    title: '新信件接收查看提醒'
    content: '发件人: %s </br> 内容描述: %s'
  # 意见发起人接收
  opinion-reply:
    url:
    query: '{}'
    arguments:
    title: '董事长信箱意见反馈回复'
    content: '回复内容: %s'
  # 协助人接收
  assistants:
    url:
    query: '{}'
    arguments:
    title: '董事长信件协助回复提醒'
    content: '发件人: %s </br> 内容描述: %s'
leave:
  type:
    transfer: b52154f9-e5ad-11ed-ac65-0800274877ca
    block: b51a67c2-e5ad-11ed-ac65-0800274877ca

#董事长信箱能收到意见反馈的boss账号
receive:
  boss: 111b0d1af37f7d60bfe9c7f2b658ef1e,036cb99d46e317d22f2ea16743285eaa,293c53e4fdcfe9ac0b9eb5e2f9c6db2e

supplier:
  tsz:
    clientId: 10001
    #客户密码
    clientSecret: 2a778c88c4024d929f5c6bdac90a9d0a
    # 客户公钥
    publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDFsRdOrsMrZiAZY7fKO/HfiMA0PdQhHNaQEyjo\
    MmNs3QUBHZ7EFuePbsrWZautZoDFdtllP+o2Wy27BXGyxek8JTw0HFwn85ybPfWy/ufDAHTUhdLO\
    DE6C/5bFYqI8un6DSjjxgIK3toGpq1t08dE2eWXOvSYeank6q2AeD68qiQIDAQAB"

    #客户私钥
    privateKey: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMWxF06uwytmIBljt8o78d+IwDQ9\
    1CEc1pATKOgyY2zdBQEdnsQW549uytZlq61mgMV22WU/6jZbLbsFcbLF6TwlPDQcXCfznJs99bL+\
    58MAdNSF0s4MToL/lsViojy6foNKOPGAgre2gamrW3Tx0TZ5Zc69Jh5qeTqrYB4PryqJAgMBAAEC\
    gYAU6QpiFDIooQC8LsP97CFFV52c6P1LE1XOn3gwN0Q0+5vP5mYor5OGpF1oGBD0omb0fAG6p+wK\
    G9LWeVjxY+WrevpfoVt2pbiEJS7BDCxWVgg3pjS6jB3Alwk4aJZqqchPRhhpg47MlpoOLi2eF5d2\
    6XpnFroGbRNfxWX1ZC74QQJBAP+OiAAhLpXafMB4Y9BKSr+tyTzIqEJqtSjiTC0ZwM6EzE8ZnVq6\
    12OGtHMoml5BS0av1T4BBRGjcDdFohSMTzUCQQDGCN4MwM8TCuBif0uHWBiXGY7Qoh/ZPeM6pSGL\
    QSmiTP2ArGqaLFIqQm0DLKO6NSAx7HZtOsV5kAkO/6TSDnSFAkEAr9k77BrpG2SEg0xUInd8h/jl\
    iFXqsgkLL17IXCBkc7cdfzB4/n2iyHFgqf0+e60iRzmm2kuJWWHFTcM0jD8gIQJAddjhCwXSNKrM\
    TNEjyS8Lsx9qdY2FFmpVxphuFch5VjQqx1/TMFwfqTZOWQ0/gZgLyKnG78mBqo2kVmCbXMVtYQJB\
    AOt7chx3YfLyEMxH4pHE6gvFKcwH0VCBjqocBpyYRv06tbU8MHUty9rrbeCdVvJePBhaZ2AgHl4J\
    bE4yBeZk1UI="

    # 唐三藏公钥
    tszPublickey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCa/ffJiiW+aQGSlWrRsAmZQG662Xj5Af2vqVT1sy7d5llNVX/\
    qU8CUy5OIN1HnYMZ2QBuLdxVTm1pIDIrVe9tf3Z0uebjbSDhTru9M8DUucIauzMqifRZotshM4ZXk4cl73BqUKnlj1IrhoQVMQZrW\
    2kiEzNXM7dntA9NGR5upTwIDAQAB"
    requestPartnerUrl: http://localhost:5005/partner
    requestAdviserUrl: http://localhost:5005/adviser