spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.192:8848
        namespace: DEV
  application:
    name: user-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zerody!@#456
    url: jdbc:mysql://192.168.100.201:3306/zero_umps?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    filters: stat
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
mybatis-plus:
  mapper-locations: classpath:/mybatis/zt/*Mapper.xml
  typeAliasesPackage: com.zerody.oauth2.pojo
  typeHandlersPackage: com.zerody.oauth2.enums.typeHandler
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
